# Copyright (C) 2023-2026 Ola Gatner
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-AmyCore-Commercial
"""Generate the complete joint CONFIG register tables from Intera's own files instead of the captures:
  sawyer_mp4_data.yaml (robot_config.jcb_hal_config: every variable of every joint, default + payload)
  param_dump.yaml      (/firmware_api/config_variables/sea/Joint<side>/<name>: module, group, variable, size)
The wire module byte is module*4 + group, the register is the variable number.
Values are the model defaults; the per-board calibration (HesOffset0, SDSCalibrationSlope,
JointAssy2RobotOffset_mRads_q10) is applied by AmyCore from each board's own DATABLOCK.
Both files are in the robot's own log export: boot the controller into the Field Service Menu (USB keyboard, Ctrl+F
during the boot countdown) and choose "Export Logs to USB" (FAT32 stick). In rethink_log_export_<serial>_<date>/:
  intera/share/sawyer_mp4_description/params/sawyer_mp4_data.yaml
  intera/log/params/param_dump.yaml
usage: genconfig.py <sawyer_mp4_data.yaml> <param_dump.yaml> <outdir> [<old table dir> to compare]"""
import sys, re, yaml, collections

data=yaml.safe_load(open(sys.argv[1]))['robot_config']
hal=data['jcb_hal_config']; boards=data['board_config']
addr={}                                                    # (side, name) -> (wire module, reg, size)
tmp=collections.defaultdict(dict)
for l in open(sys.argv[2]):
    m=re.match(r'/firmware_api/config_variables/sea/Joint(\d)/(\w+)/(group|module|size|variable): (\S+)', l)
    if m: tmp[(int(m.group(1)), m.group(2))][m.group(3)]=int(m.group(4))
for k,d in tmp.items(): addr[k]=(d['module']*4+d['group'], d['variable'], d['size'])

tables=collections.defaultdict(list)                       # node -> [(mod, reg, size, value, name)]
for joint,vars in hal.items():
    node, side = boards[joint]['nodeId'], boards[joint]['jointIndex']
    for name,v in vars.items():
        if (side,name) not in addr: print(f"  no register for {joint} {name}"); continue
        mod,reg,size=addr[(side,name)]
        tables[node].append((mod,reg,size,v['default'],f"{joint} {name}"))

out=sys.argv[3]
for node,t in sorted(tables.items()):
    t.sort()
    with open(f"{out}/intera_config_node{node}.txt","w") as f:
        f.write(f"# CONFIG for node {node}, generated by genconfig.py from sawyer_mp4_data.yaml (model defaults) + param_dump.yaml\n# module reg size value   # joint variable\n")
        for mod,reg,size,val,name in t: f.write(f"{mod:02x} {reg:02x} {size} {val}   # {name}\n")
    print(f"node {node}: {len(t)} registers")

if len(sys.argv)>4:                                         # compare with the capture-based tables
    for node,t in sorted(tables.items()):
        old={}
        for l in open(f"{sys.argv[4]}/intera_config_node{node}.txt"):
            if l.startswith('#') or not l.strip(): continue
            p=l.split(); old[(int(p[0],16),int(p[1],16))]=int(p[3])
        new={(m,r):(v,n) for m,r,s,v,n in t}
        missing=[new[k][1] for k in new if k not in old]
        extra=[k for k in old if k not in new]
        differ=[(new[k][1],old[k],new[k][0]) for k in new if k in old and old[k]!=new[k][0]]
        print(f"node {node}: {len(missing)} not in the capture table, {len(extra)} only in the capture table, {len(differ)} different values")
        for n in missing: print(f"    missing: {n}")
        for k in extra: print(f"    capture-only: module 0x{k[0]:02x} reg 0x{k[1]:02x} = {old[k]}")
        for n,o,v in differ: print(f"    differ: {n}: capture {o}, default {v}")
