# Copyright (C) 2023-2026 Ola Gatner
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-AmyCore-Commercial
# Writes build_info.cpp (version, git revision, build time) for AmyCore. Run by the custom command in CMakeLists.txt,
# only when a source file or the git HEAD changed, so a no-op build doesn't relink (which would drop the setcap caps).
execute_process(COMMAND git describe --always --dirty --tags
                WORKING_DIRECTORY ${SRC_DIR} OUTPUT_VARIABLE GIT_REV OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if (NOT GIT_REV)
    set(GIT_REV "unknown")
endif()
string(TIMESTAMP BUILD_DATE "%Y-%m-%d %H:%M")
file(WRITE ${OUT} "// generated by cmake/build_info.cmake, do not edit
#include \"build_info.h\"
const char *amyVersion     = \"${VERSION}\";
const char *amyGitRev      = \"${GIT_REV}\";
const char *amyBuildDate   = \"${BUILD_DATE}\";
const char *amyVersionLine = \"AmyCore v${VERSION} (${GIT_REV}, built ${BUILD_DATE})\";
")
